version: '3'
services:
  php:
    container_name: supermarket-test
    image: php:8.1-cli
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8000
  composer:
    image: composer:2
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: composer install --no-scripts